<a href="https://colab.research.google.com/github/Roohiashahzad/Roohia_INFO5731_Spring2020/blob/main/RoohiaShahzad_In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (1/27/2021, 20 points in total)**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [ ]:
# write your answer here

def findDuplicate(arrayOfInt):

  holder = []

  noDuplicate = -1

  for i in range(len(arrayOfInt)):
    if arrayOfInt[i] in holder:
      return arrayOfInt[i]
    else:
      holder.append(arrayOfInt[i])

  return noDuplicate

  

print(findDuplicate([1,2,3,4,4,5,6,6]))
print(findDuplicate([1,2,3,4,5,6]))
print(findDuplicate([1,2,3,4,5,6,6]))

4
-1
6


(2) Write a Python program to select all the Sundays of a specified year. (4 points)



In [ ]:
# write your answer here
from datetime import date, timedelta
def findSundays(year):
  # Jan 1 of year
  dt = date(year, 1, 1)

  #First Sunday
  dt += timedelta(days = 7 - dt.isoweekday())
  while dt.year == year:
    yield dt
    dt += timedelta(days = 7)

for i in findSundays(2021):
  print(i)


2021-01-03
2021-01-10
2021-01-17
2021-01-24
2021-01-31
2021-02-07
2021-02-14
2021-02-21
2021-02-28
2021-03-07
2021-03-14
2021-03-21
2021-03-28
2021-04-04
2021-04-11
2021-04-18
2021-04-25
2021-05-02
2021-05-09
2021-05-16
2021-05-23
2021-05-30
2021-06-06
2021-06-13
2021-06-20
2021-06-27
2021-07-04
2021-07-11
2021-07-18
2021-07-25
2021-08-01
2021-08-08
2021-08-15
2021-08-22
2021-08-29
2021-09-05
2021-09-12
2021-09-19
2021-09-26
2021-10-03
2021-10-10
2021-10-17
2021-10-24
2021-10-31
2021-11-07
2021-11-14
2021-11-21
2021-11-28
2021-12-05
2021-12-12
2021-12-19
2021-12-26


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/info5731_spring2021/blob/main/class_exercises/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)



In [115]:
# write your answer here

import csv
with open('output.csv', "w", newline = "") as outputFile:
  data_handler = csv.writer(outputFile, delimiter = ',')
  i = 1
  while i<=100:
    inputFileName = "/content/" + "ARTHROTEC." +str(i)+".txt"
    outputLineName = "ARTHROTEC"+str(i)
    inputFile = open(inputFileName).read()
    sentences = inputFile.split('\n')

    for x in sentences:
      if x =='':
        sentences.remove(x)
        
    for x in sentences:
      sentences_id = outputLineName+ " Line " + str(sentences.index(x))
      data_handler.writerow([sentences_id, x])
    
    
    i +=1



import csv
import re
rowData = [] 

with open("output.csv",'r') as inputFile:
    contentReader = csv.reader(inputFile) 
    for row in contentReader:
        new_sentence = re.sub(r"[^a-zA-Z\s\']","",row[1]) 
        new_sentence = re.sub("\s\s"," ",new_sentence) 
        row.append(new_sentence) 
        rowData.append(row)

with open("output.csv","w") as outputFile:
    data_handler = csv.writer(outputFile,delimiter=',') 
    data_handler.writerows(rowData) 


import csv
import re
userInput = input("enter a word ") 
with open('output.csv','r') as inputFile:
    contentReader = csv.reader(inputFile) 
    for row in contentReader: 
        word = " "+userInput+" "
        if word in row[2]:
            user_words = re.findall(word,row[2])
            print(row[0],row[1],len(user_words))


enter a word headache
ARTHROTEC7 Line 0 started having a severe sudden onset headache in the back of head, resulted in trip to DR, BP was extrememly high, and pulse was high as well, after three shots, and 3 clonidine to bring down bp was recommend to visit ER. 1
ARTHROTEC16 Line 4 HOWEVER: I had a very bad headache yesterday and Ibuprofen again didn't work. 1
ARTHROTEC42 Line 0 Stomach pains, chest pains, anxiety, fatigue, headache, erratic heart beat, raised blood pressure, dizziness, nausea (even when taken with food), blurred vision. 1
ARTHROTEC80 Line 0 abdominal pain, constant soreness in abdomen, headache, general stomach upset feeling that won't go away before or after eating. 1


(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [110]:

# NLTK

! pip install nltk
from nltk.tokenize import wordpunct_tokenize

test_text = "Hello, world!"
print(wordpunct_tokenize(test_text))
print("----------------------------------------------------------------------")

# Numpy
! pip install numpy
import numpy as np
n= np.arange(12)
print(n)

a_array = np.zeros((3,3))   
print(a_array)

print("----------------------------------------------------------------------")

#scipy
! pip install Scipy

from scipy import stats
import numpy as np
arr = np.array([2,4,6,8,10,12])
mean = arr.mean()
sum = arr.sum()
print (mean,sum)

print("----------------------------------------------------------------------")

#Pandas
! pip install Pandas
import pandas as pd
dataset = {
  'fruits': ["apple", "orange", "melon"],
  'sales': [100, 240, 35]
}

mysales = pd.DataFrame(dataset)

print(mysales)

print("----------------------------------------------------------------------")

#Sklearn
! pip install Sklearn
from sklearn import datasets
iris = datasets.load_iris()
print(iris.DESCR)

print("----------------------------------------------------------------------")


['Hello', ',', 'world', '!']
----------------------------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------------------------------------------------------------
7.0 42
----------------------------------------------------------------------
   fruits  sales
0   apple    100
1  orange    240
2   melon     35
----------------------------------------------------------------------
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    =======